{
 "title": "fluentd",
 "description": "cpu, memory, network, disk graphs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(fluentd_input_status_num_records_total{job=\"fluentd\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "input records - tag",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(fluentd_input_status_num_records_total{job=\"fluentd\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "input records - hostname",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(fluentd_input_status_num_records_total{job=\"fluentd\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "output records - tag",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(fluentd_output_status_num_records_total{job=\"fluentd\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "output records - hostname",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(fluentd_output_status_num_records_total{job=\"fluentd\",instance=~\"$node\"}[5m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "output buffer queue length - type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (fluentd_output_status_buffer_queue_length{job=\"fluentd\",instance=~\"$node\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "output buffer bytes - type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (fluentd_output_status_buffer_total_bytes{job=\"fluentd\",instance=~\"$node\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "output emit count - hostname",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (hostname) (irate(fluentd_output_status_emit_count{job=\"fluentd\",instance=~\"$node\"}[5m]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "output emit count - type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (irate(fluentd_output_status_emit_count{job=\"fluentd\",instance=~\"$node\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "output emit records - hostname",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (hostname) (irate(fluentd_output_status_emit_records{job=\"fluentd\",instance=~\"$node\"}[5m]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "output emit records - type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (irate(fluentd_output_status_emit_records{job=\"fluentd\",instance=~\"$node\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "output errors - type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (irate(fluentd_output_status_num_errors{job=\"fluentd\",instance=~\"$node\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "output retry count - type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (irate(fluentd_output_status_retry_count{job=\"fluentd\",instance=~\"$node\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "output retry wait - type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (irate(fluentd_output_status_retry_wait{job=\"fluentd\",instance=~\"$node\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "output write count - type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (irate(fluentd_output_status_write_count{job=\"fluentd\",instance=~\"$node\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}