{
 "title": "elasticsearch",
 "description": "Graphs for elasticsearch indices metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_indices_docs{job=\"elasticsearch\"}, cluster)"
   },
   {
    "name": "name",
    "query": "label_values(elasticsearch_indices_docs{job=\"elasticsearch\",cluster=\"$cluster\"}, name)"
   },
   {
    "name": "node",
    "query": "label_values(elasticsearch_filesystem_data_size_bytes{job=\"elasticsearch\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_flush_time_seconds{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "flush_time"
    },
    {
     "expr": "irate(elasticsearch_indices_get_exists_time_seconds{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "get_exists"
    },
    {
     "expr": "irate(elasticsearch_indices_get_missing_time_seconds{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "get_missing"
    },
    {
     "expr": "irate(elasticsearch_indices_get_time_seconds{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "get (total)"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_delete_time_seconds_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "indexing_delete"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "indexing_index"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "merges"
    },
    {
     "expr": "irate(elasticsearch_indices_refresh_time_seconds_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "refresh"
    },
    {
     "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "search_fetch"
    },
    {
     "expr": "irate(elasticsearch_indices_search_query_time_seconds{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "search_query"
    },
    {
     "expr": "irate(elasticsearch_indices_store_throttle_time_seconds_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "store_throttle"
    }
   ]
  },
  {
   "title": "count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_flush_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "flush_total"
    },
    {
     "expr": "irate(elasticsearch_indices_get_exists_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "get_exists"
    },
    {
     "expr": "irate(elasticsearch_indices_get_missing_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "get_missing"
    },
    {
     "expr": "irate(elasticsearch_indices_get_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "get (total)"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_delete_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "indexing_delete"
    },
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "indexing_index"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_docs_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "merges_docs"
    },
    {
     "expr": "irate(elasticsearch_indices_merges_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "merges"
    },
    {
     "expr": "irate(elasticsearch_indices_refresh_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "refresh"
    },
    {
     "expr": "irate(elasticsearch_indices_search_fetch_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "search_fetch"
    },
    {
     "expr": "irate(elasticsearch_indices_search_query_total{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "search_query"
    },
    {
     "expr": "irate(elasticsearch_indices_translog_operations{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "translog"
    }
   ]
  },
  {
   "title": "memory_size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_filter_cache_memory_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "filter_cache"
    },
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "fielddata"
    },
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "query_cache"
    },
    {
     "expr": "elasticsearch_indices_request_cache_memory_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "request_cache"
    },
    {
     "expr": "elasticsearch_indices_segments_memory_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "segments"
    },
    {
     "expr": "elasticsearch_indices_translog_size_in_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "translog"
    }
   ]
  },
  {
   "title": "docs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "total"
    },
    {
     "expr": "elasticsearch_indices_docs_deleted{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "deleted"
    }
   ]
  },
  {
   "title": "store_size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "store_size"
    }
   ]
  },
  {
   "title": "cpu_percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "cpu_time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_process_cpu_time_seconds_sum{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "open_files",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_open_files_count{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "open files"
    }
   ]
  },
  {
   "title": "jvm_memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_jvm_memory_max_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "max"
    },
    {
     "expr": "elasticsearch_jvm_memory_used_bytes{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "threadpool - threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_threads_count{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "threadpool - active",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_active_count{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "threadpool - queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_thread_pool_queue_count{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "threadpool - rejected",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_rejected_count{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "threadpool - completed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_thread_pool_completed_count{job=\"elasticsearch\",cluster=~\"$cluster\",name=~\"$name\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}