{
 "title": "freebsd - overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu_seconds_total{job=\"freebsd\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu_seconds_total{job=\"freebsd\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{job=\"freebsd\",mode=\"user\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "user"
    },
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{job=\"freebsd\",mode=\"system\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "system"
    },
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{job=\"freebsd\",mode=\"nice\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "nice"
    },
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{job=\"freebsd\",mode=\"interrupt\",instance=~\"$node:$port\"}[5m])) * 100",
     "legendFormat": "interrupt"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_size_bytes{job=\"freebsd\",instance=~\"$node:$port\"} - node_memory_free_bytes{job=\"freebsd\",instance=~\"$node:$port\"}) / node_memory_size_bytes{job=\"freebsd\",instance=~\"$node:$port\"} * 100",
     "legendFormat": "main"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes{job=\"freebsd\",instance=~\"$node:$port\"}[5m]))",
     "legendFormat": "transmit"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes{job=\"freebsd\",instance=~\"$node:$port\"}[5m]))",
     "legendFormat": "receive"
    }
   ]
  }
 ]
}