{
 "title": "freebsd - network",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu_seconds_total{job=\"freebsd\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu_seconds_total{job=\"freebsd\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "bytes - recieve",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{job=\"freebsd\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "bytes - transmit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes{job=\"freebsd\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "packets - recieve",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets{job=\"freebsd\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "packets - transmit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets{job=\"freebsd\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}