{
 "title": "freebsd - filesystem",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu_seconds_total{job=\"freebsd\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu_seconds_total{job=\"freebsd\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "% used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size{job=\"freebsd\",instance=~\"$node:$port\"} - node_filesystem_avail{job=\"freebsd\",instance=~\"$node:$port\"}) / node_filesystem_size{job=\"freebsd\",instance=~\"$node:$port\"} * 100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "avail",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "files",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "files_free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files_free{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}