{
 "title": "freebsd - memory",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu_seconds_total{job=\"freebsd\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu_seconds_total{job=\"freebsd\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "% used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_size_bytes{job=\"freebsd\",instance=~\"$node:$port\"} - node_memory_free_bytes{job=\"freebsd\",instance=~\"$node:$port\"}) / node_memory_size_bytes{job=\"freebsd\",instance=~\"$node:$port\"} * 100",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_size_bytes{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "main"
    },
    {
     "expr": "node_memory_swap_size_bytes{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "active, buffer, cache, wired",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_active_bytes{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "active"
    },
    {
     "expr": "node_memory_buffer_bytes{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "buffer"
    },
    {
     "expr": "node_memory_cache_bytes{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "cache"
    },
    {
     "expr": "node_memory_wired_bytes{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "wired"
    }
   ]
  },
  {
   "title": "free, inactive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_free_bytes{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_inactive_bytes{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "inactive"
    }
   ]
  },
  {
   "title": "swap_in, swap_out",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_swap_in_bytes_total{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "swap_in"
    },
    {
     "expr": "node_memory_swap_out_bytes_total{job=\"freebsd\",instance=~\"$node:$port\"}",
     "legendFormat": "swap_out"
    }
   ]
  }
 ]
}