{
 "title": "nginx_exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "nginx_exporter_process_uptime" }
   ]
  },
  {
   "title": "cpu time - user",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_exporter_process_cpu_total{job=\"nginx_exporter\",type=\"user\"}"
    }
   ]
  },
  {
   "title": "cpu time - system",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_exporter_process_cpu_total{job=\"nginx_exporter\",type=\"system\"}"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nginx_exporter_process_memory{job=\"nginx_exporter\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "cpu time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "nginx_exporter_process_cpu{job=\"nginx_exporter\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}