{
 "title": "nginx",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "requests_total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_requests_total{job=\"nginx_exporter\"}"
    }
   ]
  },
  {
   "title": "request_time_ms_total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_request_time_ms_total{job=\"nginx_exporter\"}"
    }
   ]
  },
  {
   "title": "request_count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_request_count{job=\"nginx_exporter\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "request_time - quantiles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nginx_request_time_ms{job=\"nginx_exporter\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "request_time_status - quantiles",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg (nginx_request_time_status_ms{job=\"nginx_exporter\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "request_time_status - quantile=\"0.1\"",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nginx_request_time_status_ms{job=\"nginx_exporter\",quantile=\"0.1\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "request_time_status - quantile=\"0.5\"",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nginx_request_time_status_ms{job=\"nginx_exporter\",quantile=\"0.5\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "request_time_status - quantile=\"0.9\"",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nginx_request_time_status_ms{job=\"nginx_exporter\",quantile=\"0.9\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "request_time_status - quantile=\"0.99\"",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nginx_request_time_status_ms{job=\"nginx_exporter\",quantile=\"0.99\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}