{
 "title": "memory",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu_seconds_total{job=\"node\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu_seconds_total{job=\"node\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Mem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapCached_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_SwapFree_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_CommitLimit_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Buffers, Cached, Mapped",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Mapped_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Mapped"
    }
   ]
  },
  {
   "title": "Active",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_anon_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "anon"
    },
    {
     "expr": "node_memory_Active_file_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "file"
    },
    {
     "expr": "node_memory_Active_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Inactive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Inactive_anon_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "anon"
    },
    {
     "expr": "node_memory_Inactive_file_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "file"
    },
    {
     "expr": "node_memory_Inactive_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Page",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_AnonPages_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Pages"
    },
    {
     "expr": "node_memory_AnonHugePages_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "HugePages"
    },
    {
     "expr": "node_memory_PageTables_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_Unevictable_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Unevictable"
    }
   ]
  },
  {
   "title": "Dirty, Writeback",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Dirty_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Dirty"
    },
    {
     "expr": "node_memory_Writeback_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Writeback"
    },
    {
     "expr": "node_memory_WritebackTmp_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "WritebackTmp"
    }
   ]
  },
  {
   "title": "Slab",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SReclaimable_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Reclaim"
    },
    {
     "expr": "node_memory_SUnreclaim_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Unreclaim"
    },
    {
     "expr": "node_memory_Slab_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_KernelStack_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "KernelStack"
    },
    {
     "expr": "node_memory_Mlocked_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Mlocked"
    },
    {
     "expr": "node_memory_Shmem_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Shmem"
    },
    {
     "expr": "node_memory_Bounce_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "Bounce"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{job=\"node\",instance=~\"$node:$port\"}",
     "legendFormat": "HwCorrupted"
    }
   ]
  }
 ]
}