{
 "title": "network",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_cpu_seconds_total{job=\"node\"}, instance)"
   },
   {
    "name": "port",
    "query": "label_values(node_cpu_seconds_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes - transmit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Bytes - receive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Packets - transmit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Packets - receive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Drop - transmit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Drop - receive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Errors - transmit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Errors - receive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{job=\"node\",instance=~\"$node:$port\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}